Update StringResources.zh-Hant.xaml
NickeManarin/ScreenToGif pull request #739
Opened 2020-10-07 15:32 UTC by dxball

Add a lot of missing translation, and fix words in Traditional Chinese

2020-10-07 18:02 UTC, Jerrylum requested changes
多謝您將不少的詞匯轉換到台灣以及香港等地常用的詞匯，有一些更改的建議想和您討論一下，希望您不要介意。

首先，除了比較佔位的原因外，為何將全形的冒號轉為英文的冒號呢？

其次，我發現您將所有文本結尾的句號刪除，我認為在一般短句而言，移除句號是可以接受的，但是所有有逗號的文本，我們應該將其視為一個段落，結尾應該要使用句號。例如L142：

https://github.com/NickeManarin/ScreenToGif/pull/739/commits/fb23cfcb77530e18fbc0642603e5dec0c582de84#diff-c6cd2e57a56b06a201c08207d886be40L142

再者，如果你打算將`設置`轉換為`設定`，請轉換所有詞匯。

另外，有一些更改建議我已經標示了出來，勞煩您修改一下。

期待您對此的看法以及意見，十分感謝您對 ScreenToGif 的貢獻！

2020-10-07 18:17 UTC, NickeManarin commented
Thanks for the contribution @dxball and thanks for the thoroughly review @Jerrylum.

2020-10-08 01:21 UTC, dxball commented
@Jerrylum
冒號的問題我再統一為全形冒號
句號全數移除掉是因為我發現原有的翻譯文字，句號出現的位置並不統一，所以我選擇移除所有句號，我會再調整句號的使用
稍晚我再根據您提供的意見做修正，謝謝

2020-10-08 13:31 UTC, dxball commented on ScreenToGif/Resources/Localization/StringResources.zh-Hant.xaml
> -    <s:String x:Key="S.Editor.Image.Obfuscate">模糊</s:String>
Should this icon translate to"模糊"? 
![image](https://user-images.githubusercontent.com/194673/95465247-7614d100-09ad-11eb-9d16-5927401b1d42.png)

2020-10-10 06:22 UTC, Jerrylum commented on ScreenToGif/Resources/Localization/StringResources.zh-Hant.xaml
> -    <s:String x:Key="S.Options.App.Tray.Show">在任務欄（通知區域）上顯示應用程式</s:String>
I think it is a Taskbar (任務欄)
![image](https://user-images.githubusercontent.com/12783829/95647643-b0908200-0b03-11eb-966a-6c4d93f31801.png)

---

and this is a Toolbar (工具列)
![image](https://user-images.githubusercontent.com/12783829/95647666-db7ad600-0b03-11eb-88f2-f15acd6cc17a.png)

2020-10-10 06:26 UTC, Jerrylum commented on ScreenToGif/Resources/Localization/StringResources.zh-Hant.xaml
> -    <s:String x:Key="S.Editor.Image.Obfuscate">模糊</s:String>
How about "效果"?

![image](https://user-images.githubusercontent.com/12783829/95647765-8e4b3400-0b04-11eb-8181-9ef0c2a37729.png)

2020-10-10 06:29 UTC, Jerrylum commented on ScreenToGif/Resources/Localization/StringResources.zh-Hant.xaml
> -    <s:String x:Key="S.Options.Upload.Proxy.Mode.Disabled">已禁用</s:String>
It is ok

2020-10-10 13:53 UTC, dxball commented on ScreenToGif/Resources/Localization/StringResources.zh-Hant.xaml
> -    <s:String x:Key="S.Options.App.Tray.Show">在任務欄（通知區域）上顯示應用程式</s:String>
I can't find "任務欄" in my windows 10 (locale: zh-TW)
so I change it to  "工作列" & "通知區域圖示"

https://support.microsoft.com/zh-tw/help/30031/windows-10-customize-taskbar-notification-area

![image](https://user-images.githubusercontent.com/194673/95656454-1e0ed380-0b41-11eb-8720-cf8c3e8eb112.png)

2020-10-11 10:17 UTC, Jerrylum commented on ScreenToGif/Resources/Localization/StringResources.zh-Hant.xaml
> -    <s:String x:Key="S.Options.App.Tray.Show">在任務欄（通知區域）上顯示應用程式</s:String>
agree

2020-10-11 11:03 UTC, Jerrylum commented
Thanks @dxball 
Look good to me.

2020-10-11 12:54 UTC, merged

2020-10-11 12:54 UTC, NickeManarin commented
Thank you :)